include: package:pedantic/analysis_options.yaml
analyzer:
  exclude:
    - lib/**
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true
  errors:
    todo: error
    include_file_not_found: ignore
linter:
  rules:
    return_of_invalid_type_from_closure
    public_member_api_docs
    invalid_assignment